### ISSUE TITLE
Will this work with github?

### ISSUE THREAD

**Issue by JellisHeRo** [mtigas/django-medusa#23]
I am new to this kind of thing, so I want to know if it is possible to use this on github?

**Comment by alsoicode** [comment]
Yes. I use [my fork](https://github.com/alsoicode/django-medusa) which adds static media collection to deploy to Github pages.

**Comment by JellisHeRo** [comment]
Sweet! If you dont mind me asking, what kinds of steps should I be taking to get this to github? I dont think Im understanding this medusa app very well. I understand that its a static site generator but I dont know where I should be inputting my posts, my themes and how I should set up my site for deployment. For instance, if we look at a generic static site generator set up, its something like this:

     ▸ content/
     ▸ layouts/
     ▸ static/
     config.toml

 In Medusa, I think that there is some configs that I would have to go through, reasonably, but I am stuck on the renderers. Are they supposed to derive from models in your app? I created a method via Python/Django to render markdown documents and displays them in the web, but I dont know if thats how medusa works, or if I can make some integrations. 

On another note, when using Hugo (a diff staticsitegen), I noticed that if I place any markdown file in the posts section, the site generation produces as much folders with index.html in them, with that being the webpage. Just wondering, is it like this in Medusa? .

**Comment by alsoicode** [comment]
With Medusa, you develop a Django site as you would any other, with the consideration that you're not going to be able to process dynamic content, handle POST requests, or anything else a "normal" Django site would do.

Any time you make a change to the content of your site, presumably when running the project using the local development server, you will compile out those changes to static code, which can then be pushed to your Github Pages enabled repository.

If your site has blog posts for example, you would/could edit those using Django admin running locally, then compile and push.

Renderers simply take paths, follow them, and save the result of calling the URL as a static file. Sometimes these paths come from a model instance, sometimes they are just the result of a view. For each path, a directory structure is created to mimic segmented URLs.

As an example, on my personal site: https://alsoicode.github.io/, I have a view: /work/ which returns samples of my graphic design and web projects. Each work sample has a detail: https://alsoicode.github.io/work/texas-tribune/ for example.

Medusa will create an index.html that sits in a `/work` directory, with links to each work sample, that come from the `.get_absolute_url()` method of each. Each URL segment, like `/texas-tribune`, becomes a directory, and the result of the work sample detail view is saved as an index.html in that directory.

I hope that gives you a better understanding of what's going on behind the scenes.

**Comment by JellisHeRo** [comment]
It does, thanks for this. My only issue is that get_absolute_url seems to be a very model-based method. Does this mean I have to create something from django-admin? It seems like this is what I would need to do, but if there is a way I can link urls without getting the absolute url or without models I would prefer that. I've had lots of issues trying to work with get_absolute_url(), so Ive usually worked without them.

**Comment by alsoicode** [comment]
How you get the URL patterns is up to you. `get_absolute_url` is leveraged by Django admin, but it's not a hard requirement; it's just a convenient, documented way to encapsulate getting the URL pattern for an instance of your object.

Ultimately, you're going to need to resolve the URL pattern for an object instance somehow. You may as well use the built-in mechanisms to do so, instead of re-inventing the wheel.

It sounds like perhaps you just need a bit of practice with Django's URL pattern matching, which is what `get_absolute_url` leverages. For what it's worth, I always work my patterns most to least specific and when/wherever possible, I namespace my URLs to avoid collisions.

**Comment by JellisHeRo** [comment]
Well its been days trying to find a solution and Im all out. I really dont understand whats going on with this app or what I ought to be doing with the urls. I tried using models, just to see if it works and it doesnt. I keep running into NoReverseMatch errors with get_absolute_url, even though I can see my posts just fine in localhost. So Im out of ideas. Hosting in general gets me so frustrated I want to quit...but quitting now would be admitting that I wasted all this time, so Im not quitting.

For comparing and contrasting, can you share with me your models.py, urls.py and views.py? Something that I am doing is clearly not in line with django medusa. 

**My models**
````
from django.db import models
from django.db.models import permalink
from django_markdown.models import MarkdownField
from django.core.urlresolvers import reverse
from django_bootstrap_markdown.widgets import MarkdownInput


class Category(models.Model):
    # article = models.ForeignKey('models.Post', related_name="categories", related_query_name="category")
    category_title = models.CharField(max_length=140, default='DEFAULT VALUE', blank=True, null=True)
    def __str__(self):
        return self.category_title
    class Meta:
        verbose_name = "Category" 
        verbose_name_plural = "Categories"


class EntryQuerySet(models.QuerySet):
	# This will be used for filtering everything that is published
	def published(self):
		return self.filter(publish=True)

class Post(models.Model):
    title = models.CharField(max_length=200) 
    body = MarkdownField() # formerly MarkdownField(), and TextField()
    slug = models.SlugField(max_length=200, unique=True)
    publish = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True) # Keeps track of everytime it gets saved
    objects = EntryQuerySet.as_manager() #Im allowed to do this because of the QuerySet class

    def __str__(self):
        return self.title

    @permalink
    def get_absolute_url(self):
        """ The URL to this post in the detail-based view...or in other words,
        the format in which the URL of the blog post is presented. """
        # ::: mysite.com/entry/the-posts-respective-slug
        return reverse('entry', (), kwargs={'slug': self.slug })
````

**My views.py**
````
from django.shortcuts import render
from . import models 
from django.views.generic.detail import DetailView # from the 16 min vid
from django.utils import timezone
from django.core.paginator import Paginator, InvalidPage, EmptyPage, PageNotAnInteger



class BlogDetail(DetailView):
    model = models.Post
    template_name = "post2.html"
    context_object_name = "post"


def blog(request):
	entries = models.Post.objects.all()
	paginator = Paginator(entries, 3)
	page = request.GET.get("page", '1')
   
	try: 
		entries = paginator.page(page)
	except PageNotAnInteger:
		entries = int(page)
	except ValueError: 
		page = 1
	except (InvalidPage, EmptyPage):
		entries = paginator.page(paginator.num_pages)

	# because index is out of the basic layout
	template = 'blog.html'
	context = {'posts': entries}
	return render(request, template, context)
````

**My urls.py**
````
from django.conf import settings # for development environment
from django.conf.urls import include, url
from django.conf.urls.static import static # for development environment
from django.contrib import admin
from blog.views import BlogDetail


url1 = url(r'^admin/', include(admin.site.urls))           # 1. url for "admin" page
url2 = url(r'^$', 'joins.views.home', name='home')         # 2. url for "joins" page
url3 = url(r'^markdown/', include('django_markdown.urls')) # 3. url for the "django_markdown" module
url4 = url(r'^blog/', 'blog.views.blog', name='blog') # 4. url for the "blog" page
url5 = url(r'^entry/(?P<slug>\S+)/', BlogDetail.as_view(), name="entry")


urlpatterns = [url1, url2, url3 ,url4, url5]


# For development environment
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
````

**Comment by alsoicode** [comment]
Sure, I'd be happy to help. I'm pretty slammed at the moment, but I'll do my best to take a look for you as quickly as possible.

**Comment by alsoicode** [comment]
@JellisHeRo Sorry to take so long to get back to you. Got slammed with some refactoring. Should have time to help this evening if you still need it.

**Comment by JellisHeRo** [comment]
Yes! please, i could really use it. I'd like to see your models, views, urls modules to compare with mine. Right now idk what else I need to do to get this working.

**Comment by alsoicode** [comment]
Ok, finally have some time to help.

First, I always do my URL patterns from most to least complex. This decreases the chance of colliding patterns, so I would do:

    urlpatterns = [
        url(r'^markdown/', include('django_markdown.urls')),
        url(r'^entry/(?P<slug>[-\w]+)/$', BlogDetail.as_view(), name="entry"),
        url(r'^admin/', include(admin.site.urls)),
        url(r'^blog/$', 'blog.views.blog', name='blog'),
        url(r'^$', 'joins.views.home', name='home')
    ]

Make sure you terminate patterns with `$`.

I wouldn't allow any non-whitespace character for the `slug`. Instead I use `[-\w]+` which is almost the same, but a bit more restrictive.

On the call to `reverse`, try:

    class Post(models.Model):
        . . .

        @permalink
        def get_absolute_url(self):
            return reverse('entry', args=(), kwargs={'slug': self.slug })

**Comment by kezabelle** [comment]
As I'm apparently still watching this repo:

wrapping your `get_absolute_url` underneath the `permalink` decorator is not necessary - you're already doing what `permalink` does by calling `reverse`.

You haven't shown your medusa renderers - does the site work *except* for the the medusa stage, or are you still wrapping your head around Django itself? (if so, the official docs, the users mailing list, and the IRC channel are all good support options)

**Comment by JellisHeRo** [comment]
@alsoicode  thanks for the advice regarding the urls module. With your help along with kezabelle, I got rid of that error, and now Im facing a AppRegistryNotReady error. I dont rememeber encountering this kind of error before, but its a long traceback (let me know if you would like to see it); here is the renderers.py file that I used.

```
from django_medusa.renderers import StaticSiteRenderer
from blog.models import Post
from django.core.urlresolvers import reverse


class BlogPostsRenderer(StaticSiteRenderer):
    def get_paths(self):
        # A "set" so we can throw items in blindly and be guaranteed that
        # we don't end up with dupes.
        paths =["/entry/"]

        items = Post.objects.filter(publish=True).order_by('-created')

        for item in items:
            paths.append(item.get_absolute_url())

        return paths

renderers = [BlogPostsRenderer, ]
```


@kezabelle My issue is really medusa. I found a way to get around the get_absolute_url issue when I decided to just render my django app around mere markdown files instead of a models. When I run it, it shows and it works, from what I know. I am only trying the get_absolute_urls now because I just want to get a good idea on how Medusa works with url patterns on models since I cant seem to make it work for the urls and my markdown documents in a mere folder (assuming that Medusa can function that way). Getting rid of the permalink helped, though, so the initial error I had with the get_absolute_url is gone. Thanks.
